fix: try to fix Bash errors on macOS

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
+status=0
 for test in ./tests/*; do
-	echo "run test: $test"
-	command "$test"
+	echo "test: $test"
+	if ! command "$test"; then
+		echo "test failed"
+		status=1
+	fi
 done
+exit $status
